import { FC } from "react";
import Head from "next/head";
import { Container } from "components";
import SearchBar from "../views/Home/SearchBar";
import Pagination from "../views/Home/Pagination";
import MovieList from "../views/Home/MovieList";

const Home: FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="py-5">
        <Container>
          <SearchBar />
          <MovieList />
          <Pagination />
        </Container>
      </section>
    </>
  );
};

export default Home;
