import Head from "next/head";
import { FC } from "react";
import { useAppDispatch, useAppSelector } from "store/hooks";
import { Container } from "components";
import MovieCard from "../../components/MovieCard/MovieCard";

const Home: FC = () => {
  const dispatch = useAppDispatch();
  const favoriteMovies = useAppSelector((state) => state.movies.favoriteMovies);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="py-6">
        <Container>
          <h1 className="mb-7 text-center text-3xl font-[700]">
            Favorite Movies
          </h1>
          <ul className="grid grid-cols-1 gap-y-7 gap-x-10 md:grid-cols-3 xl:grid-cols-4">
            {favoriteMovies.length ? (
              favoriteMovies.map((movie) => (
                <MovieCard key={movie.imdbID} movie={movie} />
              ))
            ) : (
              <li>
                <p>Favorite Movies not found</p>
              </li>
            )}
          </ul>
        </Container>
      </section>
    </>
  );
};

export default Home;
